### ISSUE TITLE
Basket Batch Update - action "delete" deletes all instances of the field

### ISSUE THREAD

**Issue by viola-v** [dag-hammarskjold-library/dlx-rest#1148]
Related to #1065 

The delete function doesn't work as intended - all instances of a field are deleted and not just the one with the specific values as requested.

https://github.com/dag-hammarskjold-library/dlx-rest/assets/110108422/62678515-4358-4d08-80ad-acb5a79dfe45

**Comment by meropeee** [comment]
At the latest communication(attached), we discussed that at such a case the expected behavior if the user would like to delete a selected field from a record, all the respective matching field codes from all the items of the basket will be deleted, regardless of their value/ subfields.

We did it such way out of simplicity to get the functionality out soon. Of course, the conditional case based on subfield value will be part of the Global Batch Update. 

The options we have are:
1. remove the description from the selected to be deleted field as it is misleading, so users will know that every instance of the selected code will be deleted-indicate it with a message too.
2. implement exact value check (based on all subfields?). Which cases do you face more often conditional subfields or exact match of all subfields? We can add a checkbox "Exact match" option on Deletion - this will take time to be implemented. How much do we want it to be part of the Basket Batch update?

[RE Batch Update Mockups.zip](https://github.com/dag-hammarskjold-library/dlx-rest/files/11909595/RE.Batch.Update.Mockups.zip)

**Comment by viola-v** [comment]
Thank you @meropeee for the reminder that we had indeed decided to delete all instances of the field - but as is the display is confusing, so we definitely need to discuss further!

**Comment by meropeee** [comment]
Updated requirement in the documentation: 
If a field is selected for deletion, the respective matching field codes from the selected items of the basket will be deleted only in the case that their respective subfield values are all matching to every subfield of this field.
