### ISSUE TITLE
Misleading message when deleting record: Error: Something went wrong: [object Object]

### ISSUE THREAD

**Issue by meropeee** [dag-hammarskjold-library/dlx-rest#1423]
Environment: UAT

Record is deleted but misleading message appears.

**Comment by aaronhelton** [comment]
The issue is that the app is iterating through all baskets to try to find items to delete when the record's delete method is called. In previous iterations, when the basket.get_item_by_coll_and_rid() method was called, it returned either a basket object or None, which was allowing a subscript call on it. The error message is now 

`TypeError: 'NoneType' object is not subscriptable`

So we need to either ask if the basket item is None or catch TypeError.

Otherwise the record is in fact deleted.

**Comment by viola-v** [comment]
Just to record that this is an issue in production now.
