### ISSUE TITLE
Speech records don't always sort correctly by "created" date

### ISSUE THREAD

**Issue by viola-v** [dag-hammarskjold-library/dlx-rest#1534]
Griet reported the following:

For this [query](https://metadata.un.org/editor/records/bibs/search?start=1&limit=250&sort=created&direction=desc&q=symbol%3A%22A%2FC.3%2F71%2FSR.4%22&engine=community&format=brief&subtype=speech), the results when sorted by 'created' display in this order:

![image](https://github.com/user-attachments/assets/166cf1f6-f960-4e1c-8ac9-a2e5fe665c07)

According to 998__a, the first record was created on 20170517085500:

![image](https://github.com/user-attachments/assets/00886904-5a53-4b58-bddc-9b37cfa28d5c)

However, further down in the results is this record with a creation date in 998__a of 20170516153900:

![image](https://github.com/user-attachments/assets/5a2c610d-9721-4842-984e-46beb29b1a94)

Shouldn't this record display first? Is the "created" sorting not based on 998__a?

This doesn't happen consistently, usually the order is correct, and sometimes it changes later in the day.

**Comment by jbukhari** [comment]
@viola-v Records that were created in Horizon do not have a "created" field in the current database. Therefore those records can't be sorted using that field. 

Note a related consideration with "updated". The earliest "updated" date in the database is 2020-02-14. Those are records from the initial population of the database that haven't been updated since. 

So "created" and "updated" in the database are recording what has happened in this database, not the lifetime of the metadata record. However there may be ways to combine the sort with 998 to sort the records by 998 when "created" does not exist.

**Comment by viola-v** [comment]
Not prioritizing for now, but potential solutions could be to include 998 as an additional search criteria or to move the data from 998__a into the system generated created date.

**Comment by viola-v** [comment]
Just to point out that the sorting of the [example above](https://metadata.un.org/editor/records/bibs/search?start=1&limit=250&sort=created&direction=desc&q=symbol%3A%22A%2FC.3%2F71%2FSR.4%22&engine=community&format=brief&subtype=speech) has changed now:

![image](https://github.com/user-attachments/assets/80f20da8-7366-4124-9255-ec228dfb7d04)
