### ISSUE TITLE
Certain fields aren't captured in CSV export

### ISSUE THREAD

**Issue by viola-v** [dag-hammarskjold-library/dlx-rest#1551]
When we try to export results from authority searches in CSV and limit the out to individual fields, such as 110, 111, 130 and 150, these fields aren't captured in the export file. It works when we don't limit it to certain fields. It also works for 100, 190 and 191.

**Comment by viola-v** [comment]
For this query, some 110 fields display, others don't: https://metadata.un.org/editor/records/auths/search?q=998%3A1998*+AND+110%3A*+AND+UNEP&start=1&limit=250&sort=updated&direction=desc&search=998%3A1998*+AND+110%3A*+AND+unesco&engine=community&format=brief

**Comment by aaronhelton** [comment]
The issue seems to stem, in part, from fields that have commas in them. This doesn't explain all cases, but in the query above, most 110s display in the resulting CSV; some 110s are blank; and an unknown number are truncated because of bare commas that arrived in the export from the API.

Sample export:
[export(39).csv](https://github.com/user-attachments/files/17401916/export.39.csv)

**Comment by aaronhelton** [comment]
Okay, scratch that. On further inspection, the fields that appear to be truncated are fields that have multiple subfields that aren't being concatenated.

We'll have to dig in further to see what's going wrong here.
