### ISSUE TITLE
Symbol logical field value not being saved to search index collection in one case

### ISSUE THREAD

**Issue by jbukhari** [dag-hammarskjold-library/dlx-rest#1613]
In the case of production record ID 1422239, the "symbol" logical field value is failing to be saved to the _index_symbol symbol collection. It should be saved to this collection when the bib record is saved.

**Comment by viola-v** [comment]
I think this also happened on 13 November with id:1419728.

From Joe in the UX chat: It's in the browse index now and searchable by double quotes now. It looks like some background tasks failed on record save. However, we can always retrospectively run the indexing scripts. That's what I just did in order to get it indexed correctly. Maybe we should set up these scripts to run periodically in order to catch anything missed by failed background tasks.

**Comment by jbukhari** [comment]
> Here's another current example - this time it's a [voting record](https://metadata.un.org/editor/editor?records=bibs/1422373):

> I changed the priority to critical for this one, because we risk creating duplicates...

@viola-v [It looks like it is in the browse index](https://metadata.un.org/editor/records/bibs/browse/symbol?q=a%2Fres%2F79%2F47&subtype=vote). I don't think anything has changed since you posted this. May I ask when that screen shot was taken?

**Comment by viola-v** [comment]
I took the screenshot this morning when I created the ticket... I had actually noticed it last week, but forgot to document it. Not sure what changed between this morning and now...

**Comment by jbukhari** [comment]
> I took the screenshot this morning when I created the ticket... I had actually noticed it last week, but forgot to document it. Not sure what changed between this morning and now...

I see now that both of these cases were fixed by re-running the same admin task (`build-logical-fields`). The failure of the background task should be addressed by performance and excepiton handling/logging in #1570 and #1602
