### ISSUE TITLE
Jmarc().saved does not recognize certain changes

### ISSUE THREAD

**Issue by jbukhari** [dag-hammarskjold-library/dlx-rest#310]

**Comment by jbukhari** [comment]
This prevents saving the record unless something else in the record has also changed

**Comment by jbukhari** [comment]
Addressed in PR #318 

.saved is still not detecting changed indicators, but as of #318 it will not prevent saving the record

**Comment by aaronhelton** [comment]
@jbukhari should we keep this open or do we have a different issue to address it?

**Comment by Yalshire2004** [comment]
I made some investigations : 

**0- Value level**
No issues.

**1- Subfield level**

When you create and after delete a subfield the saved button stay with the red color.

**2- Field level**

When you create a new field the saved button stay with the blue color instead of red color.

When you delete afield the saved button stay with the blue color.

**3- Indicator level**

No logic implemented at this level.

I think that we should fix those issues before sending this code in testing.

**Comment by aaronhelton** [comment]
Excellent. This looks right to me.

**Comment by aaronhelton** [comment]
Just pending indicators?
