### ISSUE TITLE
Implement validation requirements

### ISSUE THREAD

**Issue by aaronhelton** [dag-hammarskjold-library/dlx-rest#361]
There are a number of already determined validation requirements that need to be applied to the editor interface.

**Comment by aaronhelton** [comment]
Where do we display validation errors? --> Flash/message bar at the top of the screen on save. 

Right now it will show up one by one; this is fine. 

Do we highlight text along the way (e.g., before record is saved)? What does that look like? --> “syntax highlighting” is sufficient -> display more information on hover. 

Prevent entry where possible; use dropdowns/controlled lists where possible. This is a first line of defense.

**Comment by viola-v** [comment]
Since I just pasted the links to the requirement into a different ticket (#608 ), I'm pasting them here as well:

Bibs:[https://unitednations.sharepoint.com/:w:/s/MarcEditorProject/EVHcCTwbWhJLny6R76i3MJ0Bk6nwfq1MKGWb23pO9kv_4Q?e=WufmiT](url)

Auths: [https://unitednations.sharepoint.com/:w:/s/MarcEditorProject/ETZy0fYB0P1MsogXr_ECrgUBfuFDa-VfyAKYXUYfQgM7NQ?e=dg9AXD](url)

Speeches: [https://unitednations.sharepoint.com/:w:/s/MarcEditorProject/EVqcJvcxsixFv6NZ6Vo_fogBt5K6tXZ2Q_Leh4lvh8vcKQ?e=TKU7iw](url)

Votes: [https://unitednations.sharepoint.com/:w:/s/MarcEditorProject/Ec7hcVPc_DdBsa8UDKlSmwUBwLIkZFv1fV51_4z8PTBkDg?e=2ktHcL](url)
