### ISSUE TITLE
Move "Save As Workform" icon further right so it's not accidentally clicked.

### ISSUE THREAD

**Issue by aaronhelton** [dag-hammarskjold-library/dlx-rest#627]
The Save As Workform feature is not as frequently used. Move the icon to the right so it's not accidentally clicked.

**Comment by aaronhelton** [comment]
Let's take a look at the icon ordering.

**Comment by viola-v** [comment]
This came up again in this round of feedback because people clicked on the icon by mistake and then couldn't go back to the record they were working on. We should still review the overall icon ordering, but moving the one that's least used all the way to the right seems a good first step:

![image](https://user-images.githubusercontent.com/110108422/207370525-53c24b6d-8b7a-4034-bbca-2910bfe5f184.png)
