### ISSUE TITLE
Skip validations for old records

### ISSUE THREAD

**Issue by aaronhelton** [dag-hammarskjold-library/dlx-rest#864]
Technically this is possible, but is it the right policy choice? This needs further discussion.

**Comment by viola-v** [comment]
Definitely! I think it's still possible to get the scripts to that point where they don't keep us from saving records that have mistakes that don't matter. I would like to collect as many as issues as possible during the testing, but that depends on people reporting them. One solution might be to just not validate on most indicators, since most of them don't matter. To be discussed further.

**Comment by viola-v** [comment]
I chatted with Valeria and as part of her works, she updates large numbers of records and doesn't want to be slowed down by a validation issue, even if it is an important one. 

To discuss whether we can enable save for updated records with validation mistakes, but keep the current process in place when saving new records, that is they should not be saved if there are validation mistakes.

**Comment by aaronhelton** [comment]
Proposal: New records created in the editor should go through validation (and prevent saving), while records that originated in Horizon can warn on validation but allow saving.

**Comment by aaronhelton** [comment]
Also make sure this is communicated to users as they edit and create records.

**Comment by aaronhelton** [comment]
Use 998 as the discriminator.
