### ISSUE TITLE
Validation Failed-But record was saved

### ISSUE THREAD

**Issue by meropeee** [dag-hammarskjold-library/dlx-rest#979]
1. Open a bib record on Marc Editor 
2. add field 992 this String: hello test and Press Save

Expected Result:
Save should not be allowed as date format should be yyyymmdd

Failed:
with the message: Record 1366723 has been updated/saved although it shouldnt

**Comment by viola-v** [comment]
I think [this record](![image](https://user-images.githubusercontent.com/110108422/220133717-0fd92e7f-3199-4320-9d96-0b11ae1f207e.png)) was imported from Horizon (it has a 998 field)- we decided that validations could be saved with errors for records imported from Horizon (because there are so many errors in the old records), but not for newly created records in the MARC Editor. Closing
